### ISSUE TITLE
Removing orphans needs multiple iterations 

### ISSUE THREAD

**Issue by xtraeme** [void-linux/xbps#156]
Right now removing autodeps in xbps-src (xbps-remove -O) does not remove all orphaned packages in a single execution.

This needs to be fixed properly this time.

**Comment by Duncaen** [comment]
This should be fixed by https://github.com/void-linux/xbps/pull/146, as far as I see.

**Comment by LinArcX** [comment]
I have same issue. Imagine that i installed _xfce4__ desktop with all it's dependencies. After a while, i decide to remove it with `-R` option. And i want to remove all it's __.xbps__ files reside in: `/var/cache/xbps`. But in most cases `-O` doesn't do it's job very well.
When will this problem be resolved?

**Comment by pullmoll** [comment]
@LinArcX what problem? Your comment does not contain a description of an actual problem.

**Comment by LinArcX** [comment]
@pullmoll I explain it. :/
1. Install xfce4 desktop: `sudo xbps-install -S xfce4`.
2. Delete it with: `sudo xbps-remove -R xfce4`.
3. Try to remove __xbps cache directory__ and all orpahned packages with: `sudo xbps-remove -Oo`. But xfce4 and all it's dependencies still exists in there.

**Comment by pullmoll** [comment]
This is not a bug. The option `-O` removes **orphaned** packages from the cache while the `xfce4*.xbps` and its `*.sig` files in your cache are not orphans. They are still the latest and valid package files you can have and this is independent of what your intent is.

What you want is remove all traces of `xfce4*` from `/var/cache/xbps`. This is nothing a tool does for you but you'll have to do yourself.

**Comment by LinArcX** [comment]
I know I can remove them manally. But sometimes a package install multiple packages (as dependencies) with itself. For example __gnome__ or __plasma-desktop__install more than 200 packages (xfce about 100) and it's hard to find them and remove them manually. It'll better that xbps somehow handle these situations and offer us a tool or something like that to remove them safely.

**Comment by pullmoll** [comment]
I doubt anyone will implement such a function. Just zap your `/var/cache/xbps`. Any package which is required for a new install will be downloaded anyway.

**Comment by pullmoll** [comment]
Here's a script for you:
```
#!/bin/sh
CACHE=/var/cache/xbps
TMPFILE=$(mktemp)
xbps-query -l | awk '{ print $2 }' > ${TMPFILE}
for f in $(ls ${CACHE} | grep -v "\.sig$"); do
        name=$(echo "$f"|sed -e "s;\.xbps.*$;;" -e "s;\.x86_64;;" -e "s;\.noarch;;")
        if [ $(grep ${name} ${TMPFILE}) ]; then
                echo "keep: $name"
        else
                echo "rm -vf ${CACHE}/${name}*"
        fi
done
rm -f $TMPFILE
```
If you are happy with the results, remove the `echo "` in the `else` branch and let it remove files.

**Comment by xtraeme** [comment]
it's fixed in 0.57, thanks!

**Comment by Duncaen** [comment]
Its not completely fixed, there are still cases where obsoletes are not found correctly, thats why I didn't update the void package yet.

**Comment by xtraeme** [comment]
@Duncaen would be nice to create new test case. In my tests this worked fine.

**Comment by xtraeme** [comment]
@Duncaen ping

**Comment by Duncaen** [comment]
I don't have a testcase, but I think you can find a reproducible package by removing the loop in xbps-src's `remove_pkg_autodeps` function.

**Comment by Chocimier** [comment]
Some time ago test case was to install marble5 in clean masterdir.
Virtual packages was involved in bug, because its providers can be deps but not revdeps.

**Comment by xtraeme** [comment]
@Chocimier is this still relevant? so far I haven't reproduced this issue for a while

**Comment by Chocimier** [comment]
Reprodicible with xbps from master branch:
```
./xbps-src -m orphans binary-bootstrap
./xbps-src -m orphans chroot

xbps-install marble5
xbps-remove marble5
xbps-remove -o
xbps-remove -o
...
```

**Comment by xtraeme** [comment]
will try to write a test case to reproduce

**Comment by xtraeme** [comment]
I just verified this, `xbps-remove -R` works as expected, the issue is just detecting orphans.

**Comment by xtraeme** [comment]
Finally got this fixed.

**Comment by xtraeme** [comment]
Verified after installing/removing marble5 with both modes (xbps-query -O, xbps-remove -R).

```
[juan@leysa xbps]$ ./bin/xbps-query/xbps-query.static -O|wc -l
60
[juan@leysa xbps]$ ./bin/xbps-remove/xbps-remove.static -no|wc -l
60
[juan@leysa xbps]$ time ./bin/xbps-remove/xbps-remove.static -no|wc -l
60

real	0m0.454s
user	0m0.449s
sys	0m0.005s
[juan@leysa xbps]$ ./bin/xbps-remove/xbps-remove.static -no|wc -l
60
[juan@leysa xbps]$ sudo ./bin/xbps-remove/xbps-remove.static -yo &>/dev/null
[juan@leysa xbps]$ xbps-install -n marble5|wc -l
61
[juan@leysa xbps]$ sudo xbps-install -y marble5 &>/dev/null
[juan@leysa xbps]$ ./bin/xbps-remove/xbps-remove.static -Rn marble5|wc -l
61
[juan@leysa xbps]$ sudo ./bin/xbps-remove/xbps-remove.static -Ry marble5 &>/dev/null
[juan@leysa xbps]$ ./bin/xbps-query/xbps-query.static -O
[juan@leysa xbps]$
```
